#!/bin/bash

j=1
while [ -e $"DiscConfig$j.json" ]
do
 j=$((j+1))
done

echo $j

#for i in $runs
#do
#	python config_generator.py $i
#        mkdir weighted_$i_profiles
#	python run_model.py -m DiscConfig$i.json
#
#done

python config_generator.py $j
mkdir weighted_$j_profiles
python run_model.py -m DiscConfig$j.json
ffmpeg -framerate 5 -i weighted_$j_visc_%01d.png weighted_$j.avi 

chmod +x run_many
