#!/bin/bash

j=1
while [ -e $"DiscConfig$j.json" ]
do
 j=$((j+1))
done

#masses="0.2 0.1 0.05 0.02 0.01 0.005 0.002"
radii="200 100 80 30 10"

for i in $radii
do
	echo "Number assigned to this run:"
	echo $j
    # ID, radius, alpha, UV
	python config_generator.py $j $i $1 $2 $3
	python ../KeyScripts/run_model.py -m DiscConfig$j.json >> terminal_output$j.txt
	#ffmpeg -framerate 5 -i entrain_nodrift_"$j"_profiles/entrain_nodrift_"$j"_%01d.png entrain_$j.avi 
	j=$((j+1))
done

chmod +x run_many
